version: '3.9'

# run: docker-compose up --build

x-common-variables: &common-variables
  SPRING_DATASOURCE_URL: jdbc:postgresql://ep-frosty-queen-a8y975aj-pooler.eastus2.azure.neon.tech/flow?sslmode=require&channelBinding=require
  SPRING_DATASOURCE_USERNAME: flow_owner
  SPRING_DATASOURCE_PASSWORD: npg_aIV6lHZQEiw2
  JWT_SECRET: ZG9uJ3Qgc2hvb3QsIEknYW0gYSBwcm9ncmFtbWVyIQpwcm92ZSBpdC4uLgpoZWxsb3dvcmxkKCJwcmludGYiKTs
  JWT_EXPIRATION: 86400000
  FRONTEND_URL: http://localhost:3000
  AI_BACKEND_URL: http://host.docker.internal:5000
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: 'true'
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10MB
  SERVER_SERVLET_CONTEXT_PATH: /
  AUTH_SERVICE_URL: http://auth-service:8090
  EXAM_SERVICE_URL: http://exam-service:8091
  LEARNING_SERVICE_URL: http://learning-service:8092
  PROFILE_SERVICE_URL: http://profile-service:8093

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      <<: *common-variables
      SPRING_APPLICATION_NAME: api-gateway
      SERVER_PORT: 8080

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8090:8090"
    environment:
      <<: *common-variables
      SPRING_APPLICATION_NAME: auth-service
      SERVER_PORT: 8090

  exam-service:
    build:
      context: ./exam-service
    ports:
      - "8091:8091"
    environment:
      <<: *common-variables
      SPRING_APPLICATION_NAME: exam-service
      SERVER_PORT: 8091

  learning-service:
    build:
      context: ./learning-service
    ports:
      - "8092:8092"
    environment:
      <<: *common-variables
      SPRING_APPLICATION_NAME: learning-service
      SERVER_PORT: 8092

  profile-service:
    build:
      context: ./profile-service
    ports:
      - "8093:8093"
    environment:
      <<: *common-variables
      SPRING_APPLICATION_NAME: profile-service
      SERVER_PORT: 8093

  # python-server:
  #   build:
  #     context: ./python-service
  #   ports:
  #     - "5000:5000"

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     REACT_APP_API_URL: http://api-gateway:8080
  #   depends_on:
  #     - api-gateway
  #     - auth-service
  #     - exam-service
  #     - learning-service
  #     - profile-service
  #     - python-server
